[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_microros_transport = wifi
board_microros_distro = jazzy

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/basicmicro/basicmicro_arduino 